export const normalizedCommunities = [
  {
    id: 1,
    name: "Laravel Cameroun",
    location: "Cameroon",
    members: 785,
    description:
      "Laravel Cameroun is a community of developers and enthusiasts who specialize in building web applications using the Laravel framework. This community shares knowledge, organizes meetups, and collaborates on open-source projects to advance the Laravel ecosystem in Cameroon.",
    logo: "/communities/laravel-cm.png",
    tags: ["PHP", "Laravel", "MySQL"],
    featured: true,
    updated_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    links: "https://laravel.cm/",
    socialLinks: {},
  },
  {
    id: 2,
    name: "Dot NET Cameroun",
    location: "Cameroon",
    members: 1245,
    description:
      "Dot NET Cameroun is a community for .NET developers in Cameroon. It provides a platform for professionals and enthusiasts to learn, share, and develop their skills in .NET technologies, including web, desktop, and cloud applications.",
    logo: "/communities/dot-net.png",
    tags: ["C#", ".NET Core", "Azure"],
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    links: "https://dotnet.cm",
    socialLinks: {},
  },
  {
    id: 3,
    name: "Flutter & Dart Community",
    location: "Cameroon",
    members: 632,
    description:
      "The Flutter & Dart Community in Cameroon is dedicated to mobile application development using the Flutter framework and Dart programming language. Members of this community engage in collaborative projects, workshops, and knowledge-sharing sessions to enhance their expertise in building cross-platform apps.",
    logo: "/communities/flutter-cm.png",
    tags: ["Dart", "Flutter", "Mobile Dev"],
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    links: "https://chat.whatsapp.com/J5ToUhSX2ADKR9k1qyh0Vf",
    socialLinks: {
      whatsapp: "https://chat.whatsapp.com/J5ToUhSX2ADKR9k1qyh0Vf",
    },
  },
  {
    id: 4,
    name: "FOF - Douala",
    location: "Douala, Littoral",
    members: 418,
    description:
      "FOF - Douala (Friends of Figma - Douala) is a community of designers and developers who use Figma for creating user interfaces and experiences. The community provides a platform for sharing knowledge, organizing workshops, and collaborating on design projects using Figma and related tools.",
    logo: "/communities/fof-douala.png",
    tags: ["UI/UX Design", "Figma", "Prototyping"],
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    links: "https://t.me/FOF_Cameroon",
    socialLinks: { telegram: "https://t.me/FOF_Cameroon" },
  },
  {
    id: 5,
    name: "Python Cameroon",
    location: "Cameroon",
    members: 650,
    description:
      "Python Cameroon is the official Python community in Cameroon. We organize meetups, workshops, and conferences to promote Python programming, share knowledge, and build a strong Python developer community across the country.",
    logo: null,
    tags: ["Python", "Programming", "Data Science"],
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    links: "https://cm.pycon.org/en",
    socialLinks: {
      twitter: "https://x.com/PythonCameroon",
      linkedin: "https://linkedin.com/company/PythonCameroon",
      discord: "https://discord.gg/mC5zzqGmQ5",
      github: "https://github.com/PythonCameroon",
      whatsapp: "https://chat.whatsapp.com/Ckc80ophGEH0NJFmZAzDMr",
    },
  },
  {
    id: 6,
    name: "OWASP Yaounde",
    location: "Yaounde, Cameroon",
    members: 300,
    description:
      "The OWASP Yaounde chapter is dedicated to improving software security awareness in Cameroon. We work with local professionals and educational institutions to promote secure coding practices and cybersecurity education across the country.",
    logo: "/communities/owasp-yaounde-logo.jpeg",
    tags: ["Security", "OWASP", "Cybersecurity"],
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    links: "https://owasp.org/www-chapter-yaounde/",
    socialLinks: {
      linkedin: "https://www.linkedin.com/company/owasp-yaounde/posts/",
    },
  },
  {
    id: 7,
    name: "Gehmit",
    location: "Cameroon",
    members: 450,
    description:
      "Gehmit is a non-profit organization dedicated to informing, educating, and guiding students in computer science. We provide career guidance, practical skills training, and support for career transitions into ICT fields, with special focus on emerging technologies like AI.",
    logo: "/communities/gehmit-logo.png",
    tags: ["Education", "Computer Science", "ICT", "Career Development"],
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    links: "http://www.gehmit.org",
    socialLinks: { linkedin: "https://www.linkedin.com/company/gehmit/about/" },
  },
  {
    id: 8,
    name: "Grand Nord Developers Community",
    location: "Grand Nord, Cameroon",
    members: 280,
    description:
      "GNDC is a community of developers from northern Cameroon focused on promoting innovation, sharing technological skills, and solving local challenges through collaborative solutions. We bring together developers to build and create for our communities.",
    logo: "/communities/gndc-logo.webp",
    tags: ["Developers", "Innovation", "Technology", "Local Development"],
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    links: "",
    socialLinks: {
      whatsapp: "https://chat.whatsapp.com/FMUPbBkEKs24B8rE4h9xsh",
      linkedin:
        "https://www.linkedin.com/company/grand-nord-developers-community/",
      facebook:
        "https://www.facebook.com/profile.php?id=61558885960388&mibextid=LQQJ4d",
      github: "https://github.com/Grand-Nord-Developpers-Community",
    },
  },
  {
    id: 9,
    name: "Cursor Cameroun",
    location: "Yaounde, Cameroon",
    members: 150,
    description:
      "The official Cursor developer community in Cameroon. We organize events, share AI-assisted development knowledge, work on open-source projects, and help developers discover the power of Cursor for modern development workflows.",
    logo: "/communities/cursor-community-yaounde-logo.jpg",
    tags: ["AI", "Development", "Cursor", "Open Source"],
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    links: "",
    socialLinks: {
      whatsapp: "https://chat.whatsapp.com/EY4YEU5pCPBLKMRbXKZ7eJ",
    },
  },
  {
    id: 10,
    name: "Opuskrypto",
    location: "Cameroon",
    members: 320,
    description:
      "Opuskrypto provides a unified platform for crypto education and airdrop tracking in Cameroon and Africa. We simplify access to the crypto ecosystem through structured courses, airdrop discovery, and community participation management.",
    logo: "/communities/opuskrypto-logo.webp",
    tags: ["Crypto", "Blockchain", "Airdrops", "Education"],
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    links: "",
    socialLinks: {
      facebook: "https://www.facebook.com/profile.php?id=61585253817792",
      linkedin: "https://www.linkedin.com/company/opus-crypto/",
      whatsapp: "https://chat.whatsapp.com/DSgfKvG9spD9DzYQD4ICIj",
    },
  },
  {
    id: 11,
    name: "TechWomen Cameroon",
    location: "Cameroon",
    members: 500,
    description:
      "TechWomen Cameroon Alumni is dedicated to empowering women and young girls in STEM fields. We provide mentorship, networking opportunities, and resources to support women in technology careers and leadership roles.",
    logo: "/communities/techwomen_cameroon_logo.jpeg",
    tags: ["Women in Tech", "STEM", "Empowerment", "Mentorship"],
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    links: "https://www.techwomencameroon.org",
    socialLinks: {
      linkedin: "https://www.linkedin.com/company/techwomen-cameroon/posts/",
    },
  },
  {
    id: 12,
    name: "Her AI Africa",
    location: "Cameroon",
    members: 400,
    description:
      "Her AI Africa is a nonprofit organization highlighting women working in artificial intelligence across Africa. We identify women-led AI companies, promote women in AI fields, and make AI education accessible to women and girls.",
    logo: "/communities/her_ai_africa_logo.jpeg",
    tags: ["AI", "Women", "Africa", "Education"],
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    links: "https://her-ai-africa.org/",
    socialLinks: {
      linkedin: "https://www.linkedin.com/company/techwomen-cameroon/posts/",
    },
  },
  {
    id: 13,
    name: "10000 Codeurs Cameroun",
    location: "Cameroon",
    members: 600,
    description:
      "10000 Codeurs Cameroon uses digital technology to empower unemployed youth and adults transitioning careers in Cameroon. We provide coding education, skills training, and job placement support to build a stronger tech workforce.",
    logo: "/communities/10000_codeurs_logo.jpeg",
    tags: ["Coding", "Youth", "Employment", "Digital Skills"],
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    links: "https://10000codeurs.com/cameroun",
    socialLinks: {},
  },
];
